services:
  dev:
    build: .
    container_name: auto3d-dev
    restart: unless-stopped
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    # Docker Desktop 支持简写：
    gpus: all
    tty: true
    shm_size: "16g"
    environment:
      - TZ=Europe/Berlin
